version: '3'

services:
  db:
    container_name: text_rpg_db
    image: postgres:latest
    restart: always
    build:
      context: postgres
    environment:
      POSTGRES_USER: diamondik
      POSTGRES_PASSWORD: jZeg5riC
      POSTGRES_DB: text_rpg
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/